# Generated by Django 5.2.5 on 2026-01-21 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('operario', models.CharField(max_length=100, verbose_name='Operario Inspección')),
                ('maquinista', models.CharField(max_length=100, verbose_name='Maquinista')),
                ('bobina', models.CharField(blank=True, max_length=100, verbose_name='N° Bobina')),
                ('cantidad_descartada', models.PositiveIntegerField(default=0, verbose_name='Cantidad Descartada')),
                ('defecto_impresion', models.BooleanField(default=False, verbose_name='Impresión')),
                ('defecto_stamping', models.BooleanField(default=False, verbose_name='Stamping')),
                ('defecto_relieve', models.BooleanField(default=False, verbose_name='Relieve')),
                ('defecto_serigrafia', models.BooleanField(default=False, verbose_name='Serigrafía')),
                ('detalle_defecto', models.TextField(blank=True, verbose_name='Descripción del Defecto')),
                ('llego_cantidad', models.BooleanField(default=True, verbose_name='¿Se llegó a la cantidad?')),
                ('autorizo_envio', models.CharField(max_length=100, verbose_name='Autorizó Envío')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_calidad', to='ordenes_trabajo.ordencompra')),
            ],
            options={
                'verbose_name': 'Control de Calidad',
                'verbose_name_plural': 'Controles de Calidad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ImagenControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='calidad/evidencias/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='postprensa.controlcalidad')),
            ],
        ),
    ]
