# Generated by Django 5.2.5 on 2026-01-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postprensa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='orden',
            field=models.CharField(max_length=50, verbose_name='N° Orden de Trabajo'),
        ),
    ]
