# Generated by Django 5.2.5 on 2026-02-19 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postprensa', '0004_tipodefecto_defectos_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
