# Generated by Django 5.2.5 on 2026-02-19 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postprensa', '0005_controlcalidad_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionDefecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_defecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='postprensa.tipodefecto', verbose_name='Tipo de Defecto')),
            ],
            options={
                'verbose_name': 'Opción de Defecto',
                'verbose_name_plural': 'Opciones de Defecto',
                'ordering': ['tipo_defecto', 'nombre'],
                'unique_together': {('tipo_defecto', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='opciones_defecto',
            field=models.ManyToManyField(blank=True, to='postprensa.opciondefecto', verbose_name='Opciones de Defecto'),
        ),
    ]
