# Generated by Django 5.2.5 on 2026-02-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0001_initial'),
        ('postprensa', '0006_opciondefecto_controlcalidad_opciones_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidad',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes_trabajo.cliente', verbose_name='Cliente'),
        ),
    ]
