# Generated by Django 5.2.5 on 2026-02-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postprensa', '0007_controlcalidad_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidad',
            name='no_conformidad',
            field=models.CharField(blank=True, choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa')], max_length=10, null=True, verbose_name='No Conformidad'),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='nro_no_conformidad',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° referencial asociada'),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='tipo_no_conformidad',
            field=models.CharField(blank=True, choices=[('RECLAMO', 'Reclamo'), ('RECHAZO', 'Rechazo')], max_length=10, null=True, verbose_name='Tipo (Externa)'),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='autorizo_envio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Autorizó Envío'),
        ),
    ]
