# Generated by Django 5.2.5 on 2026-02-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postprensa', '0008_controlcalidad_no_conformidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, recibirá los correos automáticos al registrar controles.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Notificación por Correo',
                'verbose_name_plural': 'Notificaciones por Correo',
                'ordering': ['email'],
            },
        ),
    ]
