# Generated by Django 5.2.5 on 2026-03-03 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0003_cliente_codigo'),
        ('postprensa', '0010_alter_controlcalidad_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes_trabajo.cliente', verbose_name='Cliente'),
        ),
    ]
