# Generated by Django 5.2.5 on 2026-03-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postprensa', '0011_alter_controlcalidad_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidad',
            name='item_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Ítem'),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='variedad',
            field=models.CharField(blank=True, max_length=200, verbose_name='Variedad'),
        ),
    ]
