# Generated by Django 5.2.5 on 2026-02-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clave', models.CharField(help_text='Se usa para la URL y enlaces (sin espacios)', max_length=50, unique=True, verbose_name='ID Categoria (ej: vinos)')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título Principal')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='portfolio/muestras/', verbose_name='Imagen Muestra')),
                ('etiquetas', models.CharField(help_text='Separadas por coma. Ej: Hot Stamping Oro, Relieve Alto', max_length=255, verbose_name='Etiquetas')),
                ('fondo_css', models.CharField(blank=True, help_text='Ej: radial-gradient(circle at 70% 50%, #2a1111, #0a0a0a)', max_length=255, verbose_name='Fondo CSS (opcional)')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Muestra de Etiqueta',
                'verbose_name_plural': 'Muestras de Etiquetas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clave', models.CharField(max_length=50, unique=True, verbose_name='ID Tecnologia (ej: impresion)')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título Principal')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='portfolio/tecnologia/', verbose_name='Imagen Tecnología')),
                ('etiquetas', models.CharField(help_text='Separadas por coma.', max_length=255, verbose_name='Etiquetas')),
                ('fondo_css', models.CharField(blank=True, max_length=255, verbose_name='Fondo CSS (opcional)')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SectorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clave', models.CharField(max_length=50, unique=True, verbose_name='ID Sector (ej: bodegas)')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título Principal')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='portfolio/clientes/', verbose_name='Imagen Sector')),
                ('iconos_clases', models.CharField(blank=True, help_text='Separadas por coma. Ej: fa-solid fa-wine-glass', max_length=255, verbose_name='Clases de FontAwesome')),
                ('fondo_css', models.CharField(blank=True, max_length=255, verbose_name='Fondo CSS (opcional)')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Sector de Cliente',
                'verbose_name_plural': 'Sectores de Clientes',
                'ordering': ['orden'],
            },
        ),
    ]
