# Generated by Django 5.2.5 on 2026-02-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamuestra',
            name='video',
            field=models.FileField(blank=True, help_text='Formatos recomendados: .mp4, .webm. Si subes un video, éste se mostrará en lugar de la imagen.', null=True, upload_to='portfolio/muestras/videos/', verbose_name='Video Muestra (opcional)'),
        ),
        migrations.AlterField(
            model_name='categoriamuestra',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Dejar en blanco si se sube un video.', null=True, upload_to='portfolio/muestras/', verbose_name='Imagen Muestra'),
        ),
    ]
