# Generated by Django 5.2.5 on 2026-03-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_categoriamuestra_video_alter_categoriamuestra_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamuestra',
            name='clientes',
            field=models.CharField(blank=True, help_text='Nombres de clientes separados por coma. Ej: Bodega Zuccardi, Peñaflor, Nieto Senetiner', max_length=500, verbose_name='Clientes'),
        ),
        migrations.AlterField(
            model_name='categoriamuestra',
            name='etiquetas',
            field=models.CharField(blank=True, help_text='Separadas por coma. Ej: Hot Stamping Oro, Relieve Alto', max_length=255, verbose_name='Etiquetas'),
        ),
    ]
