# Generated by Django 5.2.5 on 2026-01-20 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes_trabajo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ancho (cm)')),
                ('alto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alto (cm)')),
                ('forma', models.CharField(choices=[('rectangulo', 'Rectángulo'), ('cuadrado', 'Cuadrado'), ('trapecio_inv', 'Trapecio Inv.'), ('circulo', 'Círculo'), ('especial', 'Especial'), ('ovalo', 'Óvalo'), ('rombo', 'Rombo'), ('cuadrado_r_2_5', 'Cuadrado R 2,5'), ('rectangulo_r_2_5', 'Rectángulo R 2.5')], default='rectangulo', max_length=50)),
                ('papel', models.CharField(max_length=100)),
                ('variedad', models.CharField(max_length=100)),
                ('archivo_muestra', models.ImageField(blank=True, null=True, upload_to='muestras/', verbose_name='Muestra')),
                ('grado_alcoholico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grado Alcohólico')),
                ('codigo_cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Cliente')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('contenido_neto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contenido Neto')),
                ('elemento', models.CharField(choices=[('etiqueta', 'Etiqueta'), ('contraetiqueta', 'Contraetiqueta'), ('cuello', 'Cuello'), ('bajo_etiqueta', 'Bajo etiqueta'), ('corbata', 'Corbata'), ('eticontra', 'Eticontra'), ('fajas', 'Fajas'), ('medalla', 'Medalla'), ('oblea', 'Oblea'), ('sticker', 'Sticker'), ('collarin', 'Collarín')], default='etiqueta', max_length=20)),
                ('serigrafia', models.BooleanField(default=False, verbose_name='Serigrafía')),
                ('stamping', models.BooleanField(default=False, verbose_name='Stamping')),
                ('relieve', models.BooleanField(default=False, verbose_name='Relieve')),
                ('bajo_relieve', models.BooleanField(default=False, verbose_name='Bajo Relieve')),
                ('gofrado', models.BooleanField(default=False, verbose_name='Gofrado')),
                ('barniz_sectorizado', models.BooleanField(default=False, verbose_name='Barniz Sectorizado')),
                ('barniz', models.CharField(blank=True, choices=[('mate_agua', 'Mate Agua'), ('brillante_agua', 'Brillante Agua'), ('semimate_agua', 'Semimate Agua'), ('mate_uv', 'Mate UV'), ('brillante_uv', 'Brillante UV')], max_length=50, null=True, verbose_name='Barniz')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordenes_trabajo.ordencompra')),
            ],
        ),
    ]
