# Generated by Django 5.2.5 on 2025-11-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorden',
            name='medidas',
        ),
        migrations.AddField(
            model_name='itemorden',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alto (cm)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorden',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ancho (cm)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorden',
            name='bajo_relieve',
            field=models.BooleanField(default=False, verbose_name='Bajo Relieve'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='forma',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorden',
            name='gofrado',
            field=models.BooleanField(default=False, verbose_name='Gofrado'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='papel',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorden',
            name='relieve',
            field=models.BooleanField(default=False, verbose_name='Relieve'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='serigrafia',
            field=models.BooleanField(default=False, verbose_name='Serigrafía'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='stamping',
            field=models.BooleanField(default=False, verbose_name='Stamping'),
        ),
    ]
