# Generated by Django 5.2.5 on 2025-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='elemento',
            field=models.CharField(choices=[('etiqueta', 'Etiqueta'), ('contraetiqueta', 'Contraetiqueta'), ('cuello', 'Cuello'), ('bajo_etiqueta', 'Bajo etiqueta'), ('corbata', 'Corbata'), ('eticontra', 'Eticontra'), ('fajas', 'Fajas'), ('medalla', 'Medalla'), ('oblea', 'Oblea'), ('sticker', 'Sticker'), ('collarin', 'Collarin')], default='etiqueta', max_length=20),
        ),
    ]
