# Generated by Django 5.2.5 on 2025-11-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_itemorden_elemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorden',
            name='forma',
            field=models.CharField(choices=[('rectangulo', 'Rectangulo'), ('cuadrado', 'Cuadrado'), ('trapecio_inv', 'Trapecio INV'), ('circulo', 'Circulo'), ('especial', 'Especial'), ('ovalo', 'Ovalo'), ('rombo', 'Rombo'), ('cuadrado_r_2_5', 'Cuadrado R 2,5'), ('rectangulo_r_2_5', 'Rectangulo R 2.5')], default='rectangulo', max_length=50),
        ),
    ]
