# Generated by Django 5.2.5 on 2025-11-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_alter_itemorden_forma'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='archivo_muestra',
            field=models.ImageField(blank=True, null=True, upload_to='muestras/', verbose_name='Muestra'),
        ),
    ]
