# Generated by Django 5.2.8 on 2025-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_itemorden_archivo_muestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='anio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Cliente'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='contenido_neto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contenido Neto'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='grado_alcoholico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grado Alcohólico'),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='elemento',
            field=models.CharField(choices=[('etiqueta', 'Etiqueta'), ('contraetiqueta', 'Contraetiqueta'), ('cuello', 'Cuello'), ('bajo_etiqueta', 'Bajo etiqueta'), ('corbata', 'Corbata'), ('eticontra', 'Eticontra'), ('fajas', 'Fajas'), ('medalla', 'Medalla'), ('oblea', 'Oblea'), ('sticker', 'Sticker'), ('collarin', 'Collarín')], default='etiqueta', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='forma',
            field=models.CharField(choices=[('rectangulo', 'Rectángulo'), ('cuadrado', 'Cuadrado'), ('trapecio_inv', 'Trapecio Inv.'), ('circulo', 'Círculo'), ('especial', 'Especial'), ('ovalo', 'Óvalo'), ('rombo', 'Rombo'), ('cuadrado_r_2_5', 'Cuadrado R 2,5'), ('rectangulo_r_2_5', 'Rectángulo R 2.5')], default='rectangulo', max_length=50),
        ),
    ]
