# Generated by Django 5.2.8 on 2025-11-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_itemorden_anio_itemorden_codigo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
