# Generated by Django 5.2.5 on 2025-12-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_ordencompra_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='barniz',
            field=models.CharField(blank=True, choices=[('mate_agua', 'Mate Agua'), ('brillante_agua', 'Brillante Agua'), ('semimate_agua', 'Semimate Agua'), ('mate_uv', 'Mate UV'), ('brillante_uv', 'Brillante UV')], max_length=50, null=True, verbose_name='Barniz'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='barniz_sectorizado',
            field=models.BooleanField(default=False, verbose_name='Barniz Sectorizado'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
